In [14]:
import numpy as np

# Sample sales dataset: [OrderID, Quantity Sold, Unit Price]
sales_data = np.array([
    [1001, 10, 15.5],
    [1002, 5, 20.0],
    [1003, 8, 12.0],
    [1004, 15, 10.0],
    [1005, 7, 18.0],
    [1006, 12, 14.5],
    [1007, 6, 22.0],
    [1008, 9, 16.0]
])

print("Sales Dataset:\n", sales_data)



Sales Dataset:
 [[1001.    10.    15.5]
 [1002.     5.    20. ]
 [1003.     8.    12. ]
 [1004.    15.    10. ]
 [1005.     7.    18. ]
 [1006.    12.    14.5]
 [1007.     6.    22. ]
 [1008.     9.    16. ]]


In [15]:
quantity = sales_data[:, 1]
unit_price = sales_data[:, 2]

revenue = quantity * unit_price

total_sales = np.sum(revenue)
average_sales = np.mean(revenue)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)


Total Sales: 1077.0
Average Sales: 134.625


In [16]:
print("First 3 Records:\n", sales_data[:3])
print("Last 2 Records:\n", sales_data[-2:])
print("Quantities Only:\n", sales_data[:, 1])


First 3 Records:
 [[1001.    10.    15.5]
 [1002.     5.    20. ]
 [1003.     8.    12. ]]
Last 2 Records:
 [[1007.    6.   22.]
 [1008.    9.   16.]]
Quantities Only:
 [10.  5.  8. 15.  7. 12.  6.  9.]


In [17]:
mean_sales = np.mean(revenue)
median_sales = np.median(revenue)
variance_sales = np.var(revenue)
std_dev_sales = np.std(revenue)

print("Mean Revenue:", mean_sales)
print("Median Revenue:", median_sales)
print("Variance:", variance_sales)
print("Standard Deviation:", std_dev_sales)


Mean Revenue: 134.625
Median Revenue: 138.0
Variance: 632.734375
Standard Deviation: 25.154211873958605


In [18]:
revenue_broadcast = sales_data[:, 1] * sales_data[:, 2]
print("Revenue using Broadcasting:\n", revenue_broadcast)

Revenue using Broadcasting:
 [155. 100.  96. 150. 126. 174. 132. 144.]


In [21]:
# Apply 10% discount and calculate new revenue
discounted_price = unit_price * 0.9
new_revenue = quantity * discounted_price

print("New Revenue after 10% Discount:\n", new_revenue)


New Revenue after 10% Discount:
 [139.5  90.   86.4 135.  113.4 156.6 118.8 129.6]
